//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiScaleExporter.MAUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSnippets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSnippets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiScaleExporter.MAUI.Resources.Localization.AppSnippets", typeof(AppSnippets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is an open source community project and I have no affiliation with Garmin..
        /// </summary>
        internal static string AboutGarmin {
            get {
                return ResourceManager.GetString("AboutGarmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the bluetooth address of the scale, and your data in the settings. Stand on your scale. Measure yourself. Mi Body Composition Scale is active up to 15 min after the measurement..
        /// </summary>
        internal static string AboutMeasureInstruction {
            get {
                return ResourceManager.GetString("AboutMeasureInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then you can review your data and upload it to Garmin Cloud. If you do not have Mi scale and just want to manually insert the data, you can so..
        /// </summary>
        internal static string AboutUpload {
            get {
                return ResourceManager.GetString("AboutUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate External API Address.
        /// </summary>
        internal static string AlternateExternalAPIAddress {
            get {
                return ResourceManager.GetString("AlternateExternalAPIAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Metabolism (kCal):.
        /// </summary>
        internal static string BasalMetabolosimKCal {
            get {
                return ResourceManager.GetString("BasalMetabolosimKCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Address.
        /// </summary>
        internal static string BluetoothAddress {
            get {
                return ResourceManager.GetString("BluetoothAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body age (years).
        /// </summary>
        internal static string BodyAgeYears {
            get {
                return ResourceManager.GetString("BodyAgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Fat (%).
        /// </summary>
        internal static string BodyFatPercent {
            get {
                return ResourceManager.GetString("BodyFatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type.
        /// </summary>
        internal static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone mass (Kg).
        /// </summary>
        internal static string BoneMassPercent {
            get {
                return ResourceManager.GetString("BoneMassPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a coffee.
        /// </summary>
        internal static string BuyMeACoffee {
            get {
                return ResourceManager.GetString("BuyMeACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Search.
        /// </summary>
        internal static string CancelSearch {
            get {
                return ResourceManager.GetString("CancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Lukasz Swiderski 2023.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be obtained. try again.
        /// </summary>
        internal static string DataCouldNotBeObtained {
            get {
                return ResourceManager.GetString("DataCouldNotBeObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like this app and would you like to support it?.
        /// </summary>
        internal static string DoYouLikeAndWouldYouLikeToSupport {
            get {
                return ResourceManager.GetString("DoYouLikeAndWouldYouLikeToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Body Composition Form.
        /// </summary>
        internal static string GarminBodyCompositionForm {
            get {
                return ResourceManager.GetString("GarminBodyCompositionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Form.
        /// </summary>
        internal static string GarminForm {
            get {
                return ResourceManager.GetString("GarminForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Settings.
        /// </summary>
        internal static string GarminSettings {
            get {
                return ResourceManager.GetString("GarminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to scan.
        /// </summary>
        internal static string GoToScan {
            get {
                return ResourceManager.GetString("GoToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Cannot Sync. Missing Cookies.
        /// </summary>
        internal static string HelpCannotSync2FA {
            get {
                return ResourceManager.GetString("HelpCannotSync2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You probably have 2FA enabled. It&apos;s not supported. Please turn it off if you want to use this application..
        /// </summary>
        internal static string HelpCannotSync2FADescription {
            get {
                return ResourceManager.GetString("HelpCannotSync2FADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Coffee.
        /// </summary>
        internal static string HelpCoffee {
            get {
                return ResourceManager.GetString("HelpCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind that this is my hobby project. It was created for my inner needs and I believe it may be useful to others as well. I do not receive any compensation for creating and maintaining this project. If you want to support the development or thank me, you can buy me a coffee..
        /// </summary>
        internal static string HelpCoffeeDescription {
            get {
                return ResourceManager.GetString("HelpCoffeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. How to connect to the scale.
        /// </summary>
        internal static string HelpConnect {
            get {
                return ResourceManager.GetString("HelpConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Bluetooth address of the scale in settings. Set the correct age/height/gender values. Measure yourself. The scale is active for up to 15 minutes after measurement..
        /// </summary>
        internal static string HelpConnectDescription {
            get {
                return ResourceManager.GetString("HelpConnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth address can be found in Zepp Life &gt; Profile &gt; My devices &gt; Mi Body Composition Scale &gt; Bluetooth address (hold to copy).
        /// </summary>
        internal static string HelpConnectDescription2 {
            get {
                return ResourceManager.GetString("HelpConnectDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. External Api.
        /// </summary>
        internal static string HelpExternalApi {
            get {
                return ResourceManager.GetString("HelpExternalApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External API is used as a proxy for older Android phones (9 or lower). The default address is https://frog01-20364.wykr.es/. You can host your own version of the API and this app will send the data to your system instead of Garmin. Check out the project repository for more information..
        /// </summary>
        internal static string HelpExternalApiDescription {
            get {
                return ResourceManager.GetString("HelpExternalApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Feedback &amp; Contact.
        /// </summary>
        internal static string HelpFeedback {
            get {
                return ResourceManager.GetString("HelpFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you found a bug, need a feature or have an idea, share it with me at the project repository..
        /// </summary>
        internal static string HelpFeedbackDescription {
            get {
                return ResourceManager.GetString("HelpFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Garmin and Xiaomi.
        /// </summary>
        internal static string HelpGarminAndXiaomi {
            get {
                return ResourceManager.GetString("HelpGarminAndXiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is an open source community project and I have no affiliation with Garmin or Xiaomi. You use it at your own risk. You can always check out the source code on Github..
        /// </summary>
        internal static string HelpGarminAndXiaomiDescription {
            get {
                return ResourceManager.GetString("HelpGarminAndXiaomiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. How It works.
        /// </summary>
        internal static string HelpHowItWorks {
            get {
                return ResourceManager.GetString("HelpHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App pass your data, email and password directly to Garmin Cloud or via external API server. The API does not store or log anything, it&apos;s just a middleware between this App and Garmin services..
        /// </summary>
        internal static string HelpHowItWorksDescription {
            get {
                return ResourceManager.GetString("HelpHowItWorksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Strange results? (Like 10kg only).
        /// </summary>
        internal static string HelpStrangeResults {
            get {
                return ResourceManager.GetString("HelpStrangeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have the Mi Body Composition Scale 2. Disable the &apos;Weight small object&apos; option in Zepp Life.
        /// </summary>
        internal static string HelpStrangeResultsDescription {
            get {
                return ResourceManager.GetString("HelpStrangeResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Results different from Zepp Life.
        /// </summary>
        internal static string HelpZeppLifeDriference {
            get {
                return ResourceManager.GetString("HelpZeppLifeDriference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the age/height/gender parameters - should be identical in both apps. But even then, the values may be slightly different because we do not use the exact algorithm used by Xiaomi, but an alternative open source algorithm..
        /// </summary>
        internal static string HelpZeppLifeDriferenceDescription {
            get {
                return ResourceManager.GetString("HelpZeppLifeDriferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal Weight (Kg):.
        /// </summary>
        internal static string IdealWeightKg {
            get {
                return ResourceManager.GetString("IdealWeightKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Code.
        /// </summary>
        internal static string MFACode {
            get {
                return ResourceManager.GetString("MFACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Body Composition Scale 1 / 2.
        /// </summary>
        internal static string MiBodyCompositionScale {
            get {
                return ResourceManager.GetString("MiBodyCompositionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Scale.
        /// </summary>
        internal static string MiScale {
            get {
                return ResourceManager.GetString("MiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Scale Data.
        /// </summary>
        internal static string MiScaleData {
            get {
                return ResourceManager.GetString("MiScaleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Scale Exporter.
        /// </summary>
        internal static string MiScaleExporter {
            get {
                return ResourceManager.GetString("MiScaleExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Smart Scale.
        /// </summary>
        internal static string MiSmartScale {
            get {
                return ResourceManager.GetString("MiSmartScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle Mass (Kg).
        /// </summary>
        internal static string MuscleMassKg {
            get {
                return ResourceManager.GetString("MuscleMassKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One click - Scan &amp; Upload.
        /// </summary>
        internal static string OneClickScanUpload {
            get {
                return ResourceManager.GetString("OneClickScanUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Help.
        /// </summary>
        internal static string OpenHelp {
            get {
                return ResourceManager.GetString("OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to use Bluetooth is required to scan..
        /// </summary>
        internal static string PermissionBluetoothRequired {
            get {
                return ResourceManager.GetString("PermissionBluetoothRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to use Location (Bluetooth) is required to scan..
        /// </summary>
        internal static string PermissionLocationRequired {
            get {
                return ResourceManager.GetString("PermissionLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein (%):.
        /// </summary>
        internal static string ProteinPercent {
            get {
                return ResourceManager.GetString("ProteinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Model.
        /// </summary>
        internal static string ScaleModel {
            get {
                return ResourceManager.GetString("ScaleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Settings.
        /// </summary>
        internal static string ScaleSettings {
            get {
                return ResourceManager.GetString("ScaleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Ads Banner.
        /// </summary>
        internal static string SettingsHideAds {
            get {
                return ResourceManager.GetString("SettingsHideAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Debug Info during scan.
        /// </summary>
        internal static string ShowDebug {
            get {
                return ResourceManager.GetString("ShowDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Measure.
        /// </summary>
        internal static string StopMeasure {
            get {
                return ResourceManager.GetString("StopMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of measurement.
        /// </summary>
        internal static string TimeOfMeasurement {
            get {
                return ResourceManager.GetString("TimeOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to Garmin Cloud.
        /// </summary>
        internal static string UploadToGarminCloud {
            get {
                return ResourceManager.GetString("UploadToGarminCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use External API.
        /// </summary>
        internal static string UseExternalAPI {
            get {
                return ResourceManager.GetString("UseExternalAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values that will not be sent to the cloud:.
        /// </summary>
        internal static string ValuesThatWillNotBeSentToTheCloud {
            get {
                return ResourceManager.GetString("ValuesThatWillNotBeSentToTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visceral fat.
        /// </summary>
        internal static string VisceralFat {
            get {
                return ResourceManager.GetString("VisceralFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the project repository.
        /// </summary>
        internal static string VisitProjectRepository {
            get {
                return ResourceManager.GetString("VisitProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water (%).
        /// </summary>
        internal static string WaterPercent {
            get {
                return ResourceManager.GetString("WaterPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (Kg).
        /// </summary>
        internal static string WeightKg {
            get {
                return ResourceManager.GetString("WeightKg", resourceCulture);
            }
        }
    }
}
